### ISSUE TITLE
precos_ipca - missing information

### ISSUE THREAD

**Issue by thiagomendesrosa** [tbrugz/ribge#2]
Hi,

Using "precos_ipca" funcion, for 2006 year, we get only first 6 months.

Looking up the code, 

precos_ipca <- function(ano, dir=NULL) {
  if(ano<1991) {
    stop(paste("data not avaiable for year",ano))
  }
  resource <- ifelse(ano<=1999, "IA47_BR_PERC",
              ifelse(ano<=2006, "IA48_BR_PERC",
              ifelse(ano<=2011, "IA55_BR_PERC",
              "IA59_BR_PERC")))
  # FIXME: what about boundary years (1999 & 2006)? (2011/2012 is not a problem...)
  file <- util.downloadSeries(resource, dir = dir)

  loc <- readr::locale(decimal_mark = ",")
  df <- readr::read_tsv(file, locale = loc)
  #return(df)
  df <- inflacao.transform.df(df)
  df[df$ano==ano,]
}

one half of 2006 is inside "IA48_BR_PERC" file and the other is inside "IA55_BR_PERC" file. Same issue with 1999. Indeed, there is an observation in the code about that.

Is it possible to solve that? (maybe intersecting boundaries in the code)

Thanks in advance!

**Comment by tbrugz** [comment]
Thanks for spotting that, should be fixed in latest version
