### ISSUE TITLE
Error in download.file(url, filename_download) :    não foi possível abrir a URL ....

### ISSUE THREAD

**Issue by rtheodoro** [tbrugz/ribge#3]
Olá! Muito interessante e útil este pacote! Obrigado por disponibilizar!

Entretanto, não estou conseguindo baixar os dados. Consegui apenas a população de 2010.

Quando tento baixar o PIB, tenho esse erro:

```
> pib2010 <- pib_municipios(2010)
tentando a URL 'ftp://ftp.ibge.gov.br/Pib_Municipios/2017/base/base_de_dados_2010_2017_xls.zip'
Error in download.file(url, filename_download) : 
  não foi possível abrir a URL 'ftp://ftp.ibge.gov.br/Pib_Municipios/2017/base/base_de_dados_2010_2017_xls.zip'
Além disso: Warning message:
In download.file(url, filename_download) :
  cannot open URL 'ftp://ftp.ibge.gov.br/Pib_Municipios/2017/base/base_de_dados_2010_2017_xls.zip': FTP status was '500 Unknown Error'
```

E quando eu tento baixar a população (diferente de 2010) , eu tenho:

```
> pop2012  <- populacao_municipios(2012)
tentando a URL 'ftp://ftp.ibge.gov.br/Estimativas_de_Populacao/Estimativas_2012/estimativa_2012_DOU_28_08_2012_xls.zip'
Error in download.file(url, filename_download) : 
  não foi possível abrir a URL 'ftp://ftp.ibge.gov.br/Estimativas_de_Populacao/Estimativas_2012/estimativa_2012_DOU_28_08_2012_xls.zip'
Além disso: Warning message:
In download.file(url, filename_download) :
  cannot open URL 'ftp://ftp.ibge.gov.br/Estimativas_de_Populacao/Estimativas_2012/estimativa_2012_DOU_28_08_2012_xls.zip': FTP status was '500 Unknown Error'

> pop2020 <- populacao_municipios(2020)
tentando a URL 'ftp://ftp.ibge.gov.br/Estimativas_de_Populacao/Estimativas_2020/estimativa_dou_2020.xls'
Error in download.file(url, filename_download) : 
  não foi possível abrir a URL 'ftp://ftp.ibge.gov.br/Estimativas_de_Populacao/Estimativas_2020/estimativa_dou_2020.xls'
Além disso: Warning message:
In download.file(url, filename_download) :
  cannot open URL 'ftp://ftp.ibge.gov.br/Estimativas_de_Populacao/Estimativas_2020/estimativa_dou_2020.xls': FTP status was '500 Unknown Error'

```

Penso que talvez o IBGE tenha mudado dos links de acesso, não sei. 

Aproveitando, conhecem algum pacote que ajude a pegar dados do TabNet? (http://tabnet.datasus.gov.br/cgi/deftohtm.exe?popsvs/cnv/popbr.def)

Obrigado.

**Comment by tbrugz** [comment]
Olá, testei agora e consegui carregar informações de população e PIB dos municipíos. Talvez tenha sido um problema momentâneo no servidor, por  exemplo

Consegues acessar diretamente os arquivos no browser ou com curl/wget? Ex: `ftp://ftp.ibge.gov.br/Estimativas_de_Populacao/Estimativas_2020/estimativa_dou_2020.xls` ou `http://ftp.ibge.gov.br/Estimativas_de_Populacao/Estimativas_2020/estimativa_dou_2020.xls`

Sobre dados do datasus, nunca trabalhei, mas essa thread parece ter coisas interessantes:
https://dadosabertos.social/t/como-obter-e-tratar-dados-do-datasus/66

**Comment by rtheodoro** [comment]
Obrigado pela resposta!

Também não estava conseguindo pegar os arquivos direto, mas agora está dando certo.

Vou dar uma olhada no link, obrigado!
